/**
 * Every column of every table, as PostgREST sees it.
 *
 * Generated by scripts/generate-column-map.mjs — do not hand-edit, regenerate
 * after a migration and read the diff.
 *
 * This exists because an endpoint that spreads a request body into a write
 * fails on the first field that is not a column, and fails in the vocabulary
 * of the database rather than of the person using it. Grace was told "could
 * not find user id" while saving a rehearsal dinner, because the form had
 * picked up a userId field and rehearsal_dinner has no such column. Every save
 * had failed that way since May and nothing said so.
 *
 * Use `onlyColumns` on anything that writes a caller-supplied object.
 */

export const TABLE_COLUMNS = {
  "accommodations": ["availability", "booking_platform", "created_at", "distance", "id", "name", "price_per_night", "price_per_person", "rating", "sleeps"],
  "activity_log": ["activity_type", "created_at", "details", "id", "user_id", "wedding_id"],
  "allergy_registry": ["allergy", "caterer_alerted", "created_at", "guest_name", "id", "notes", "severity", "sort_order", "staying_overnight", "updated_at", "wedding_id"],
  "bar_recipes": ["created_at", "id", "ingredients", "name", "notes", "servings_basis", "source_type", "source_url", "wedding_id"],
  "bar_shopping_list": ["category", "checked", "created_at", "from_calculator", "id", "item_name", "notes", "quantity", "sort_order", "unit", "wedding_id"],
  "bedroom_assignments": ["guest_friday", "guest_saturday", "id", "notes", "room_description", "room_name", "sort_order", "updated_at", "wedding_id"],
  "borrow_catalog": ["category", "created_at", "description", "id", "image_filename", "image_url", "item_name"],
  "ceremony_order": ["id", "notes", "participant_name", "role", "section", "side", "sort_order", "updated_at", "walk_with", "wedding_id"],
  "client_errors": ["component", "fingerprint", "first_seen_at", "id", "last_seen_at", "message", "notes", "release", "seen_count", "stack", "status", "url", "user_agent", "user_email", "wedding_id"],
  "contact_messages": ["body", "contact_id", "contact_name", "created_at", "direction", "duration_secs", "email_address", "external_id", "id", "kind", "occurred_at", "phone_number", "shared_at", "shared_note_id", "shared_with_couple", "subject", "summary", "wedding_id"],
  "contracts": ["created_at", "document_date", "extracted_text", "file_type", "filename", "gmail_message_id", "id", "source", "storage_path", "superseded_by", "supersedes_id", "vendor_id", "vendor_key", "vendor_name", "vendor_type", "version", "wedding_id"],
  "couple_photos": ["created_at", "id", "image_url", "uploaded_by", "wedding_id"],
  "day_of_media": ["caption", "category", "created_at", "filename", "id", "mime_type", "size_bytes", "sort_order", "storage_path", "url", "wedding_id"],
  "decor_inventory": ["goes_home_with", "id", "item_name", "leaving_it", "notes", "sort_order", "source", "space_name", "updated_at", "wedding_id"],
  "direct_messages": ["content", "created_at", "id", "is_read", "read_at", "sender_id", "sender_type", "wedding_id"],
  "enquiries": ["answers", "calendly_event_uri", "converted_at", "created_at", "email", "guest_estimate", "heard_about", "id", "meeting_at", "meeting_kind", "meeting_location", "name", "notes", "outcome_notes", "package_interest", "partner_email", "partner_name", "phone", "preferred_date", "source", "status", "suggested_wedding_id", "suggestion_dismissed", "suggestion_reason", "updated_at", "used_calculator", "wedding_id"],
  "feature_gaps": ["context", "created_at", "description", "feature_area", "id", "status", "user_id"],
  "gmail_tokens": ["access_token", "created_at", "expiry_date", "id", "refresh_token", "updated_at"],
  "guest_meal_options": ["created_at", "display_order", "id", "label", "wedding_id"],
  "guest_tag_options": ["color", "created_at", "display_order", "id", "label", "wedding_id"],
  "ingest_review": ["candidates", "confidence", "created_at", "excerpt", "external_id", "id", "occurred_at", "payload", "phone_number", "reason", "resolved_at", "resolved_by", "resolved_wedding_id", "source", "status", "suggested_wedding_id", "title"],
  "inspo_gallery": ["caption", "category", "created_at", "display_order", "id", "image_url", "updated_at", "uploaded_by", "wedding_id"],
  "knowledge_base": ["active", "category", "content", "created_at", "description", "id", "subcategory", "title", "updated_at"],
  "makeup_schedule": ["hair_start_time", "id", "makeup_start_time", "notes", "participant_name", "role", "sort_order", "updated_at", "wedding_id"],
  "manor_assets": ["created_at", "description", "file_name", "id", "mime_type", "sort_order", "storage_path", "title"],
  "messages": ["content", "created_at", "id", "is_team_note", "sender", "user_id"],
  "notifications": ["body", "created_at", "email_sent", "id", "is_read", "recipient_id", "recipient_type", "title", "type", "wedding_id"],
  "onboarding_progress": ["checklist_item_completed", "couple_photo_uploaded", "created_at", "first_message_sent", "id", "inspo_uploaded", "onboarding_dismissed", "updated_at", "vendor_added", "wedding_id"],
  "planning_checklist": ["category", "completed_at", "completed_by", "completed_via", "created_at", "display_order", "due_date", "id", "is_completed", "is_custom", "task_text", "updated_at", "wedding_id"],
  "planning_notes": ["category", "content", "created_at", "id", "source_message", "status", "user_id", "wedding_id"],
  "processed_emails": ["body_text", "from_email", "gmail_message_id", "id", "processed_at", "subject", "wedding_id"],
  "processed_quo_messages": ["body_text", "direction", "id", "phone_number", "processed_at", "quo_message_id", "wedding_id"],
  "processed_zoom_meetings": ["id", "match_confidence", "match_reason", "matched_by", "meeting_topic", "participant_names", "processed_at", "transcript_text", "wedding_id", "zoom_meeting_id"],
  "profiles": ["created_at", "custom_role_term", "email", "id", "is_admin", "name", "phone", "role", "wedding_date", "wedding_id"],
  "recipes": ["created_at", "id", "ingredients", "instructions", "notes", "source", "source_url", "tags", "title", "user_id"],
  "rehearsal_dinner": ["bar_type", "created_at", "decor_source", "food_notes", "food_type", "guest_count", "high_chairs_count", "high_chairs_needed", "id", "linens_source", "location", "location_notes", "notes", "renting_china", "renting_flatware", "seating_type", "table_layout", "updated_at", "using_disposables", "wedding_id"],
  "scheduled_reminders": ["body", "created_at", "fired", "id", "scheduled_for", "title", "user_id"],
  "section_finalisations": ["couple_finalised", "couple_finalised_at", "id", "section", "staff_finalised", "staff_finalised_at", "updated_at", "wedding_id"],
  "sheet_sync_log": ["applied_at", "applied_by", "choice", "entry_id", "error", "executed", "id", "op_type", "table_name", "wedding_id"],
  "shuttle_schedule": ["dropoff_location", "dropoff_time", "id", "notes", "pickup_location", "pickup_time", "run_label", "seat_count", "sort_order", "updated_at", "wedding_id"],
  "storefront_items": ["affiliate_link", "category", "color_options", "created_at", "description", "id", "image_url", "is_active", "pick_name", "pick_type", "product_type", "sort_order"],
  "sync_jobs": ["detail", "failed", "finished_at", "heartbeat_at", "id", "kind", "last_error", "last_item", "matched", "needs_review", "processed", "started_at", "status", "total", "trigger"],
  "table_layouts": ["ceremony_plan", "created_at", "elements", "id", "name", "updated_at", "wedding_id"],
  "uncertain_questions": ["added_to_kb", "admin_answer", "answered_at", "answered_by", "client_message", "client_message_id", "client_notified_at", "confidence_level", "created_at", "id", "kb_category", "kb_subcategory", "notified_by", "question", "sage_response", "user_id", "wedding_id"],
  "usage_logs": ["created_at", "endpoint", "id", "input_tokens", "model", "output_tokens", "user_id", "wedding_id"],
  "vendor_checklist": ["arrival_time", "contract_date", "contract_document_date", "contract_path", "contract_uploaded", "contract_url", "created_at", "departure_time", "id", "instagram", "is_booked", "notes", "updated_at", "vendor_contact", "vendor_id", "vendor_name", "vendor_type", "wedding_id", "worked_here_before"],
  "vendor_contact_evidence": ["dismissed", "first_seen", "id", "kind", "last_seen", "seen_count", "source", "source_detail", "value", "value_key", "vendor_id", "wedding_id"],
  "vendor_merge_review": ["candidate_id", "created_at", "evidence", "id", "reason", "resolved_at", "status", "vendor_id"],
  "vendors": ["aliases", "availability_note", "bio", "categories", "category", "contact", "created_at", "edit_token", "email", "facebook", "featured", "has_multiple_events", "id", "instagram", "internal_notes", "is_budget_friendly", "is_local", "is_published", "is_recommended", "last_vendor_update", "logo_url", "merged_into", "name", "notes", "phone", "photos", "portal_invite_count", "portal_invited_at", "pricing_info", "serves_chinese", "serves_indian", "special_expiry", "special_offer", "website"],
  "venue_settings": ["address_line1", "address_line2", "arrival_note", "cell_service_note", "created_at", "footer_credit", "google_maps_url", "id", "logo_url", "parking_note", "tagline", "updated_at", "venue_description", "venue_name", "website_url"],
  "walkthrough_items": ["applied_at", "applied_row_id", "applied_table", "apply_error", "confidence", "created_at", "id", "kind", "proposed", "section", "source_text", "status", "summary", "updated_at", "walkthrough_id", "wedding_id"],
  "walkthrough_media": ["caption", "created_at", "duration_secs", "id", "kind", "storage_path", "transcript", "url", "walkthrough_id", "wedding_id"],
  "walkthroughs": ["attendees", "created_at", "created_by", "enquiry_id", "id", "kind", "occurred_on", "organised_at", "raw_notes", "shared_at", "shared_summary", "status", "updated_at", "wedding_id"],
  "wedding_borrow_selections": ["created_at", "id", "item_id", "wedding_id"],
  "wedding_budget": ["categories", "created_at", "id", "is_shared", "total_budget", "updated_at", "wedding_id"],
  "wedding_contacts": ["created_at", "created_by", "email", "id", "ingest_calls", "ingest_email", "name", "notes", "phone", "phone_digits", "relationship", "updated_at", "wedding_id"],
  "wedding_details": ["arbor_choice", "ceremony_location", "ceremony_notes", "contract_checkin", "contract_checkout", "contract_max_rehearsal", "contract_max_wedding", "contract_overnights", "contract_rehearsal_hours", "contract_wedding_hours", "created_at", "dog_sitter_name", "dog_sitter_time", "dogs_coming", "dogs_description", "favors_description", "high_chairs_count", "high_chairs_needed", "id", "partner1_parents", "partner1_parents_met", "partner1_social", "partner2_parents", "partner2_parents_met", "partner2_social", "providing_cake_cutter", "providing_cake_cutter_notes", "providing_cake_topper", "providing_champagne_glasses", "providing_charger_plates", "providing_table_numbers", "reception_notes", "seating_method", "send_off_notes", "send_off_type", "unity_table", "updated_at", "wedding_colors", "wedding_id", "wedding_party_count_1", "wedding_party_count_2"],
  "wedding_documents": ["byte_size", "created_at", "extracted_text", "filename", "id", "kind", "page_count", "parse_error", "parsed_at", "sections", "storage_path", "supersedes_id", "text_hash", "uploaded_by", "version", "wedding_id"],
  "wedding_guest_care": ["data", "id", "updated_at", "wedding_id"],
  "wedding_guests": ["address", "created_at", "dietary_restrictions", "email", "first_name", "id", "is_plus_one", "last_name", "meal_choice", "notes", "party_id", "phone", "plus_one_dietary", "plus_one_meal_choice", "plus_one_name", "plus_one_of", "plus_one_rsvp", "rsvp", "rsvp_extras", "table_assignment", "table_id", "tags", "updated_at", "wedding_id"],
  "wedding_internal_notes": ["content", "created_at", "id", "wedding_id"],
  "wedding_party": ["blurb", "created_at", "group_label", "guest_id", "id", "include_on_website", "member_name", "role", "sort_order", "wedding_id"],
  "wedding_photos": ["caption", "created_at", "id", "sort_order", "storage_path", "tags", "uploaded_by", "url", "wedding_id"],
  "wedding_staffing": ["answers", "created_at", "friday_bartenders", "friday_extra_hands", "friday_total", "id", "saturday_bartenders", "saturday_extra_hands", "saturday_total", "total_cost", "total_staff", "updated_at", "wedding_id"],
  "wedding_tables": ["centerpiece_notes", "chair_sash", "chair_sash_color", "cocktail_tables", "created_at", "dance_floor_size", "extra_tables", "guest_count", "guests_per_table", "head_table", "head_table_placement", "head_table_size", "id", "is_draft", "kids_count", "kids_table", "layout_notes", "linen_color", "linen_drop", "linen_notes", "linen_venue_choice", "lounge_area", "napkin_color", "runner_style", "seating_data", "sweetheart_table", "table_numbers_style", "table_shape", "updated_at", "wedding_id"],
  "wedding_timeline": ["ceremony_start", "created_at", "id", "notes", "reception_end", "reception_start", "timeline_data", "updated_at", "wedding_id"],
  "wedding_website_settings": ["accent_color", "access_password", "ceremony_time", "created_at", "dress_code", "dress_code_note", "faq_items", "font_pair", "footer_message", "hero_pretext", "id", "kids_policy", "our_story", "plus_one_policy", "published", "reception_time", "registry_links", "rsvp_config", "rsvp_deadline", "rsvp_note", "section_order", "show_accommodations", "show_dress_code", "show_faq", "show_gallery", "show_registry", "show_rsvp", "show_schedule", "show_story", "show_things_to_do", "show_transport", "show_wedding_party", "signature_cocktail", "slug", "the_proposal", "theme", "things_to_do", "unplugged_ceremony", "updated_at", "wedding_id", "welcome_message"],
  "weddings": ["archived", "bar_notes", "couple_names", "created_at", "created_by", "escalation_handled_at", "event_code", "google_sheets_link", "honeybook_link", "id", "last_activity", "last_activity_type", "partner1_name", "partner2_name", "plated_meal", "project_name", "wedding_date", "worksheet_budget_alignment", "worksheet_guest_rules", "worksheet_priorities"],
  "zoom_tokens": ["access_token", "created_at", "expiry_date", "id", "refresh_token", "updated_at"],
};

/**
 * The parts of `body` that are actually columns of `table`.
 *
 * Anything dropped is returned in `ignored` rather than swallowed, because a
 * dropped key is usually a client sending something harmless and occasionally
 * the field that was meant to save. Callers should log it.
 *
 * An unknown table returns the body untouched: a missing generated entry must
 * not quietly empty a write. Regenerate instead.
 */
export function onlyColumns(table, body) {
  const columns = TABLE_COLUMNS[table];
  if (!columns) return { fields: { ...body }, ignored: [], unknownTable: true };
  const fields = {};
  const ignored = [];
  for (const [k, v] of Object.entries(body || {})) {
    if (columns.includes(k)) fields[k] = v;
    else ignored.push(k);
  }
  return { fields, ignored, unknownTable: false };
}
