/**
 * server/lib/spreadsheet.js replaced the xlsx library (unfixable
 * prototype-pollution and ReDoS advisories, see AUDIT-2026-09-14.md item 20)
 * with exceljs. This checks parseSpreadsheet() against the shape the old
 * xlsx-based parseSeatingBuffer relied on:
 *   - one entry per sheet, keyed by sheet name
 *   - each sheet's rows as an array of arrays (the old `header: 1` shape),
 *     header row included, untouched — callers decide what a header is
 *   - a fully blank row is dropped entirely (the old `blankrows: false`)
 *   - a numeric cell comes back as a JS number, a date cell as a JS Date
 *   - a formula cell comes back as its cached result, never the formula text
 *     or an exceljs `{ formula, result }` object
 *
 * The fixture is generated by tests/fixtures/generate-seating-fixture.mjs and
 * committed as tests/fixtures/seating-import.xlsx; regenerate it with
 * `node tests/fixtures/generate-seating-fixture.mjs` if the shape changes.
 *
 * Run with: npm run test:unit
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseSpreadsheet } from '../../server/lib/spreadsheet.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const fixturePath = path.join(here, '../fixtures/seating-import.xlsx');
const fixtureBuffer = readFileSync(fixturePath);

test('both sheets in the workbook are reported by name', async () => {
  const { sheetNames } = await parseSpreadsheet(fixtureBuffer, { originalname: 'seating-import.xlsx' });
  assert.deepEqual(sheetNames, ['Guests', 'Notes']);
});

test('the header row survives untouched — callers decide what a header is', async () => {
  const { sheets } = await parseSpreadsheet(fixtureBuffer, { originalname: 'seating-import.xlsx' });
  assert.deepEqual(sheets.Guests.rows[0], ['Table', 'Seat', 'Name', 'RSVP Date', 'RSVP']);
});

test('a fully blank row is dropped, matching the old blankrows:false behaviour', async () => {
  const { sheets } = await parseSpreadsheet(fixtureBuffer, { originalname: 'seating-import.xlsx' });
  // Header + Alice + Bob = 3. The blank row the fixture writes between them
  // does not appear as a fourth, empty row.
  assert.equal(sheets.Guests.rows.length, 3);
  assert.equal(sheets.Guests.rowCount, 3);
});

test('a numeric cell comes back as a number, not a string', async () => {
  const { sheets } = await parseSpreadsheet(fixtureBuffer, { originalname: 'seating-import.xlsx' });
  const seat = sheets.Guests.rows[1][1];
  assert.equal(typeof seat, 'number');
  assert.equal(seat, 1);
});

test('a date cell comes back as a Date, same as xlsx with cellDates:true', async () => {
  const { sheets } = await parseSpreadsheet(fixtureBuffer, { originalname: 'seating-import.xlsx' });
  const rsvpDate = sheets.Guests.rows[1][3];
  assert.ok(rsvpDate instanceof Date, 'expected a Date instance');
  assert.equal(rsvpDate.toISOString(), '2026-06-01T00:00:00.000Z');
});

test('a formula cell comes back as its cached result, not a {formula,result} object', async () => {
  const { sheets } = await parseSpreadsheet(fixtureBuffer, { originalname: 'seating-import.xlsx' });
  const rsvp = sheets.Guests.rows[2][4];
  // This is the one place exceljs and xlsx genuinely differ: exceljs's raw
  // cell.value for a formula is `{ formula, result }`; the old xlsx library's
  // sheet_to_json only ever surfaced `result` (the cached computed value).
  // cellToValue() in spreadsheet.js unwraps it so callers never see the
  // difference. Left as a plain assertion, this test would fail loudly if
  // that unwrapping were ever removed.
  assert.equal(rsvp, 'Yes');
  assert.equal(typeof rsvp, 'string');
});

test('a CSV buffer is read without a workbook wrapper, headers and blank rows behave the same way', async () => {
  const csv = 'Table,Seat,Name,RSVP\nHead Table,1,Alice Smith,Yes\n\nHead Table,2,Bob Jones,No\n';
  const { sheetNames, sheets } = await parseSpreadsheet(Buffer.from(csv), {
    originalname: 'guests.csv',
    mimetype: 'text/csv',
  });
  assert.equal(sheetNames.length, 1);
  const rows = sheets[sheetNames[0]].rows;
  assert.deepEqual(rows[0], ['Table', 'Seat', 'Name', 'RSVP']);
  // Same blank-row drop as the workbook path: 3 rows, not 4.
  assert.equal(rows.length, 3);
  // exceljs's CSV reader infers types the way xlsx's CSV parser did — a
  // plain digit string becomes a number — but a CSV cell carries no format
  // code the way a real .xlsx cell does, so a date column in a CSV is not
  // guaranteed to come back as a Date the way it does for an actual
  // workbook; this fixture avoids relying on that by using an RSVP column
  // instead of a date one. Any CSV import that needs a date column read
  // reliably should parse that column explicitly rather than trust cell
  // typing.
  assert.equal(typeof rows[1][1], 'number');
});

test('mimetype, not just extension, is enough to pick the CSV path', async () => {
  const csv = 'Table,Name\nHead Table,Alice Smith\n';
  // No usable extension on the filename — this is what some browsers send
  // for a pasted CSV. The old xlsx.read() auto-detected the format from the
  // buffer's content; parseSpreadsheet falls back to mimetype for the same
  // case, since exceljs has no equivalent auto-detection.
  const { sheetNames } = await parseSpreadsheet(Buffer.from(csv), {
    originalname: 'upload',
    mimetype: 'text/csv',
  });
  assert.equal(sheetNames.length, 1);
});
